### ISSUE TITLE
Asking for Input again and again

### ISSUE THREAD

**Issue by awais922609** [psauxx/Vulnnr#3]
Hi I hope you are fine. I am facing an issue that this tool is asking again and again for input and no process is being done. Image is attached can you help me please ?
![Capture](https://user-images.githubusercontent.com/69464258/129151287-bc806520-fd6c-4a76-aa89-b155cb8d64b9.PNG)

**Comment by Hail2Hydra** [comment]
Your not giving the correct commands go Type Help it'll show you exactly what you are doing wrong annd how to correct it

**Comment by awais922609** [comment]
Thanks for the Help...
